<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SmartOrderAPI.Data\SmartOrderAPI.Data.csproj" />
    <ProjectReference Include="..\SmartOrderAPI.Entities\SmartOrderAPI.Entities.csproj" />
  </ItemGroup>

</Project>
